# Generated by Django 4.0.4 on 2022-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=300)),
                ('phone', models.IntegerField(max_length=200)),
                ('nom', models.CharField(max_length=300)),
            ],
        ),
    ]
