# Generated by Django 4.0.4 on 2022-04-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_house_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='emails',
            field=models.EmailField(max_length=300, null=True),
        ),
    ]
